### ISSUE TITLE
For cloud, can we auto populate the mddb data?

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog-maxmind-plugin#3]
We think this plugin may be a good generic thing most teams would want to use.

However there are a fair amount of setup steps (signup for maxmind, download the DB, upload).

Can we hydrate these datasources for our users automatically? It looks like it's [permitted in their licensing ](https://dev.maxmind.com/geoip/geoip2/geolite2/#License)as long as we add that attribution tag to the screens that reference its use (so probably the configuration tab)

cc: @Twixes

**Comment by Twixes** [comment]
Yep! We don't actually need attribution, since we've got the redist license courtesy of @piemets. As for hydration, it will very soon be built into the plugin server for optimal UX https://github.com/PostHog/plugin-server/pull/247. Then a plugin like the new https://github.com/PostHog/posthog-plugin-geoip will be able to enable IP location data enrichment with no configuration.
